services:
  # Backend Service (FastAPI)
  - type: web
    name: globe-view-initiate-3d-scad
    env: python
    plan: free
    pythonVersion: 3.11
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_ENV
        value: production
      - key: PORT
        value: 8000
      - key: HOST
        value: 0.0.0.0
      - key: OPENROUTER_API_KEY
        sync: false  # Set this in Render dashboard
    healthCheckPath: /api/health
    autoDeploy: true
    branch: main

  # Frontend Service (Static Site)
  - type: web
    name: globe-view-initiate-3d-scad-1
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://globe-view-initiate-3d-scad.onrender.com
      - key: VITE_APP_NAME
        value: 3D World Explorer
      - key: VITE_APP_VERSION
        value: 1.0.0
    autoDeploy: true
    branch: main
    routes:
      - type: rewrite
        source: /api/*
        destination: /index.html
      - type: rewrite
        source: /*
        destination: /index.html