services:
  # Backend Python API
  - type: web
    name: globe-esri-api
    runtime: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: CORS_ORIGINS
        value: https://globe-esri-frontend.onrender.com
      - key: HOST
        value: 0.0.0.0
    healthCheckPath: /api/health

  # Frontend React App  
  - type: web
    name: globe-esri-frontend
    runtime: node
    plan: free
    buildCommand: |
      npm ci
      npm run build
    startCommand: npx vite preview --host 0.0.0.0 --port $PORT --strictPort
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: VITE_API_BASE_URL
        value: https://globe-esri-api.onrender.com 